name: ci

on:
  push:
    branches: [ main ]

env:
  IMAGE_TAG: "1.0.2"

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: Build with Maven
        run: mvn -B -ntp clean install
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: jar-file
          path: target/admin-1.0.0.jar
          if-no-files-found: error
          retention-days: 7

  pack:
    runs-on: ubuntu-24.04
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: jar-file
          path: target
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/admin-api:${{ env.IMAGE_TAG }}
            ${{ secrets.DOCKERHUB_USERNAME }}/admin-api:latest

  bump-manifest:
    runs-on: ubuntu-24.04
    needs: [pack]
    steps:
      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: devapihub/argocd
          token: ${{ secrets.GH_PAT_PUSH }}
          ref: main

      - name: Install yq
        run: |
          YQ_VERSION=v4.44.3
          curl -sL https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64 -o /usr/local/bin/yq
          chmod +x /usr/local/bin/yq
          yq --version

      - name: Update image tag in manifest
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
          IMAGE_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/admin-api
          FILE: app/admin-api/k8s/admin-api-deployment.yaml
          CONTAINER: admin-api
        run: |
          test -f "$FILE" || { echo "Not found: $FILE"; exit 1; }
          # set image về <IMAGE_REPO>:<IMAGE_TAG> cho container tên admin-api
          yq -i '
            (.spec.template.spec.containers[] 
              | select(.name == env(CONTAINER)) 
              | .image) = (env(IMAGE_REPO) + ":" + env(IMAGE_TAG))
          ' "$FILE"
          echo "Changed:"
          git --no-pager diff -- "$FILE" || true

      - name: Commit & push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add app/admin-api/k8s/admin-api-deployment.yaml
          git commit -m "chore(admin-api): bump image to ${IMAGE_TAG}" || echo "No changes to commit"
          git push
